name: Backend CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  App_Name: "nest-list-notes"
  Service_Name: "api-notes"
  Node_Version: "22"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del Repositorio
        uses: actions/checkout@v4
      
      - name: Mostrar Variables
        run: |
          echo "App: ${{ env.App_Name }}"
          echo "Servicio: ${{ env.Service_Name }}"
          echo "Node: ${{ env.Node_Version }}"
          echo "Rama: ${{ github.ref_name }}"

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.Node_Version }}
          cache: "npm"
          cache-dependency-path: backend/api-notes/package-lock.json

      - name: Verify files
        working-directory: backend/api-notes
        run: |
          pwd
          ls -la
          ls -la backend/api-notes
          
      - name: Instalar Dependencias
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build