name: Backend CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  show-variables:
    uses: ./.github/workflows/reusable-build.yml 

  build-and-test:
    needs: show-variables
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: backend/api-notes

    steps:
      - name: Checkout del Repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: backend/api-notes/package-lock.json

      - name: Instalar Dependencias
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build