name: Reusable Build

on:
  workflow_call:
    inputs:
      service_name:
        description: "Nombre del servicio"
        required: true
        type: string
      node_version:
        description: "Versión de Node.js a usar"
        required: false
        type: string
        default: "22"

env:
  App_Name: "nest-list-notes"
  Service_Name: ${{ inputs.service_name }}
  Node_Version: ${{ inputs.node_version }}

jobs:
  print-variables:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar Variables de Entorno
        run: |
          echo "App: ${{ env.App_Name }}"
          echo "Servicio: ${{ env.Service_Name }}"
          echo "Node: ${{ env.Node_Version }}"
          echo "Rama: ${{ github.ref_name }}"

      - name: Variables del Repositorio
        run: |
          echo "Entorno: ${{ vars.DEPLOY_ENV }}"
          echo "Descripción: ${{ vars.PROJECT_DESCRIPTION }}"